#!/bin/bash

. scripts/lib/common.sh

echo "[PGSQL] Renaming DB: $DB to $DB-${DATE_TIME}"
psql -h $HOST -p $PORT -U $USERNAME -d template1 -c "ALTER DATABASE $DB RENAME TO \"${DB}-${DATE_TIME}\";"
check_status $?
echo "[PGSQL] Creating new DB: $DB"
psql -h $HOST -p $PORT -U $USERNAME -d template1 -c "create database $DB"
check_status $?

