#!/bin/bash -e

. scripts/lib/common.sh

type mvn >/dev/null 2>&1 || { echo >&2 "ERROR: I require 'mvn' but it's not installed. Aborting."; exit 1; }

[ $# -eq 0 ] && echo "ERROR: No parameter provided" && exit 2


function drop_and_create_db
{
    scripts/lib/drop-create-db
}

function show_help
{
    echo "The following options are:"
    echo "    fresh: Renames current database and create a new one"
    echo "    help: Show this help"
}

case "$1" in
    'fresh')
	drop_and_create_db
	check_status $?
	;;
    'help')
	show_help
	;;
    '*')
	echo "ERROR: Unknown parameter $1"
	show_help
	exit 2
	;;
esac

